FROM ensemblorg/ensembl-vep:release_93
LABEL maintainer="luk.zim91@gmail.com"

USER root
COPY install_scripts/install_base_root.sh /tmp
COPY install_scripts/install_base_vep.sh /tmp
RUN chmod +x /tmp/install_base_root.sh && \
    chmod +x /tmp/install_base_vep.sh && \
    /tmp/install_base_root.sh

USER vep
COPY vep.ini /opt/vep.ini
RUN /tmp/install_base_vep.sh

