FROM lukaszimmermann/clinical-reporting-base:latest
LABEL maintainer="luk.zim91@gmail.com"

USER vep
COPY apps/reporting /opt/reporting
COPY apps/templater /opt/templater
COPY report_generate.py /opt

# install ReportApp and templater
RUN chmod -R u+w /opt && \
    git clone https://github.com/PersonalizedOncology/ClinicalReportR.git && \
    mv  ClinicalReportR/ReportApp .. && \
    rm -rf ClinicalReportR && \
    chmod +x /opt/ReportApp/reporting.R && \
    mv /opt/ReportApp/clinicalreporting_docxtemplater /opt/templater

WORKDIR /opt/vep/src/ensembl-vep
ENTRYPOINT [ "python", "/opt/report_generate.py" ]
