Bootstrap: docker
From: ensemblorg/ensembl-vep:latest

%runscript

    echo "I can put here whatever I want to happen when the user runs my container!"
    exec echo "Hello Monsoir Meatball" "$@"

%environment
  PERL5LIB=/home/vep/loftee-0.3-beta:/home/vep/src/bioperl-live-release-1-6-924
  export PERL5LIB

%files
settings.py
run.py
vep_docker.ini
make_report.sh
reporting.sh

%post
apt-get update -y
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
apt-get install -y \
  apt-transport-https \
  libcairo2-dev \
  libcurl4-openssl-dev \
  libpq-dev \
  libreoffice \
  libssh2-1-dev \
  libxml2-dev \
  locales \
  nodejs \
  npm \
  python3 \
  python3-pip \
  r-base \
  samtools

apt-get update -y
locale-gen "en_US.UTF-8"

echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-3.6.list
apt-get update -y
apt-get install -y mongodb-org
mkdir -p /data/db
mongod --fork --logpath /mongolog

cd /data
wget https://raw.githubusercontent.com/PersonalizedOncology/clinicalReporting_DB_RESTAPI/master/mongo-seed/driver_db_dump.json

mongoimport \
  --host localhost \
  --db clinical_reporting \
  --collection biograph_genes \
  --jsonArray \
  --file /data/driver_db_dump.json \
  --drop

# FileDeploy
cd /home/vep/src/ensembl-vep/
git pull
git checkout release/91
./INSTALL.pl -a acf -s homo_sapiens -y GRCh37
./INSTALL.pl -a p -g LoFtool
cd /data

# Move everything to data
wget http://www.broadinstitute.org/~konradk/loftee/human_ancestor.fa.rz
wget http://www.broadinstitute.org/~konradk/loftee/human_ancestor.fa.rz.fai
wget https://raw.githubusercontent.com/Ensembl/VEP_plugins/release/90/LoFtool_scores.txt
wget https://www.broadinstitute.org/%7Ekonradk/loftee/phylocsf.sql.gz
gunzip phylocsf.sql.gz
mv /home/vep/.vep/homo_sapiens /data


# REST api
pip3 install --upgrade pip
pip3 install simplejson
pip3 install gunicorn
pip3 install eve
mkdir /api
mv /settings.py /api/settings.py
mv /run.py /api/run.py

# Clinical Reporting pipeline

# Set up R
# echo "deb http://cran.rstudio.com/bin/linux/ubuntu xenial/" >> /etc/apt/sources.list
# echo "deb http://ftp.halifax.rwth-aachen.de/ubuntu xenial-backports main restricted universe" >> /etc/apt/sources.list'
Rscript -e 'install.packages(c("dplyr", "dtplyr", "tidyr", "stringr", "splitstackshape", "flextable", "optparse", "readr", "RCurl", "devtools", "log4r"), dependencies = TRUE, repos = "https://cloud.r-project.org")'
Rscript -e 'devtools::install_github("jeremystan/tidyjson")'
Rscript -e 'devtools::install_github("davidgohel/officer")'
Rscript -e 'source("https://bioconductor.org/biocLite.R"); biocLite(c("VariantAnnotation", "rjson"), ask = FALSE, suppressUpdates = TRUE)'


cd /home/vep
wget https://github.com/konradjk/loftee/archive/v0.3-beta.zip
unzip v0.3-beta.zip
rm v0.3-beta.zip
cp loftee-0.3-beta/LoF.pm /home/vep/.vep/Plugins
cpanm DBD::SQLite
export PERL5LIB="/home/vep/loftee-0.3-beta/:$PERL5LIB"
mv /vep_docker.ini /home/vep/.vep/vep.ini
mv /make_report.sh /home/vep
mv /reporting.sh /home/vep
chown -R vep:vep /home/vep
chmod +x /home/vep/make_report.sh
chmod +x /home/vep/reporting.R
